export const inspirations = [
    'I always thought I was good at reading people, but then she looked me straight in the eye and lied without a second of hesitation...',
    'We swore we\'d never talk about what happened that night, but every time I see a rubber chicken, I remember everything...',
    'I should\'ve known things were about to go downhill when the magician whispered, \'I\'ve never actually tried this trick before...\'',
    'The thing about making a dramatic exit is that you need to know where the door is...',
    'I was ready to apologize, but then I realized—he had no idea what I had done...',
    'They say your life flashes before your eyes when you\'re in danger, but all I could think about was whether I had locked my front door...',
    'I used to believe that everything happens for a reason, but then I met Steve, and now I\'m not so sure...',
    'The moment I hit \'send,\' I knew I had made a terrible, terrible mistake...',
    'Some people have family heirlooms; my family has a curse we don\'t talk about...',
    'It was all going great until the waiter came back and said, \'Sir, this is your fourth free sample, and we\'re starting to notice...\'',
    'I always thought I was a patient person, but after ten minutes of listening to him explain the plot of a movie I had already seen, I wasn\'t so sure...',
    'I can handle awkward situations, but even I didn\'t know what to say when my date\'s ex walked in wearing the exact same shirt as me...',
    'There are two types of people in this world—those who read the instructions first and those who end up like me, covered in glue...',
    'It wasn\'t until I got home that I realized I had spent the entire day with a price tag stuck to my shirt...',
    'I was never superstitious, but after that night, I always knock on wood just in case...',
    'I should\'ve been paying attention, but in my defense, the dog was wearing sunglasses, and that\'s not something you just ignore...',
    'He told me to \'just trust him,\' which, in hindsight, was probably the biggest mistake of my life...',
    'I thought I was over it, but then I saw her name pop up on my phone, and suddenly, I wasn\'t...',
    'The problem with giving people second chances is that sometimes, they prove why you shouldn\'t have...',
    'If there\'s one thing I\'ve learned in life, it\'s this—never assume the tiny button in an unfamiliar car does nothing...',
    'I should have known something was wrong when the cat and the dog were both staring at the same empty corner of the room...',
    'They say you should never meet your heroes, but no one warned me about accidentally insulting them...',
    'I always thought I could talk my way out of anything, but then I heard myself say, \'It\'s not what it looks like!\' and realized I had no idea what I was even explaining...',
    'Everything was going fine until the GPS calmly announced, \'You have arrived,\' and I was standing in the middle of a cornfield...',
    'The worst part wasn\'t that I fell; it was that I fell in slow motion, making awkward eye contact with everyone as I went down...',
    'I should have been paying attention to the instructions, but in my defense, I was too distracted by the fact that the instructor only had one eyebrow...',
    'I don\'t know what\'s worse—the fact that I sent the wrong message, or the fact that I realized it exactly two seconds too late...',
    'I never really believed in karma until I laughed at someone tripping and immediately walked into a glass door...',
    'There\'s something deeply unsettling about getting a text that just says, \'We need to talk...\'',
    'I thought I was prepared for anything, but I wasn\'t prepared for an entire marching band to come down the street right as I started my speech...',
    'I can\'t explain why, but I knew from the moment I walked into that party that something was going to go terribly wrong...',
    'I used to think I was good at reading people, but then she smiled at me like she knew something I didn\'t, and I suddenly felt very, very small...',
    'The first rule of trying to sneak out is to make sure you don\'t trip over the cat...',
    'I always thought I\'d be the kind of person to react well in an emergency, but then the fire alarm went off and I grabbed a sandwich before leaving...',
    'I had rehearsed exactly what I was going to say, but the moment I opened my mouth, my brain decided to improvise...',
    'It wasn\'t until I was halfway through my presentation that I realized my shirt was inside out...',
    'The way he looked at me, I knew he either recognized me or I owed him money...',
    'I should have walked away, but curiosity always wins against common sense...',
    'The universe has a way of humbling you, which is how I ended up getting stuck in a child\'s swing at the park...',
    'I thought I was alone in the house, but then I heard someone clear their throat behind me...',
    'The waiter\'s face told me everything I needed to know—I had definitely mispronounced that word...',
    'I never understood the phrase \'a sinking feeling\' until I watched my phone slide into the pool in slow motion...',
    'It started with a simple bet, and somehow ended with a police officer asking me, \'Is this your chicken?\'...',
    'The problem with spontaneous decisions is that they usually come back to haunt you...',
    'I wasn\'t eavesdropping on their conversation… but when someone whispers, \'We can\'t let them find out,\' you kind of have to listen...',
    'The thing about giving advice is that people actually expect you to take your own...',
    'I thought I could fix it before anyone noticed, but judging by the look on their face, I was already too late...',
    'The moment I saw the email subject line, I knew my weekend plans had just changed...',
    'If there\'s one thing I\'ve learned, it\'s that \'trust me\' is never a good enough reason to go along with a plan...',
    'I knew I was in trouble when even my reflection looked disappointed in me...',
    'We were supposed to be on a relaxing vacation, so why were we running from security guards?...',
    'Some people learn patience through meditation; I learned it by waiting for my toast to pop while already late for work...',
    'It started with an innocent question, but by the time he was done explaining, I was questioning everything I knew about the world...',
    'I knew I had messed up when my dog gave me that \'Are you serious right now?\' look...',
    'It\'s one thing to forget someone\'s name, but it\'s another to realize you\'ve been confidently calling them the wrong name for six months...',
    'I thought I could just blend in and quietly leave, but then the host announced, \'Before you go, we have a surprise for you!\'...',
    'I never really believed in fate, but when I ran into the same stranger three times in one day, I started reconsidering...',
    'Somewhere between the second and third slice of cake, I completely lost control of my life choices...',
    'I\'ve done a lot of questionable things in my life, but saying \'I don\'t need a shopping list\' is by far the most reckless...',
    'The problem with telling a \'harmless little lie\' is that eventually, you have to remember it...',
    'I was ready to storm out dramatically, but then I couldn\'t figure out how to open the door...',
    'They say never look back, but when you hear footsteps behind you at night, you definitely should...',
    'I wasn\'t trying to be funny, but when I tripped and landed perfectly in a chair, the entire room burst into applause...',
    'I didn\'t mean to start a debate, but apparently, my opinion on pineapple pizza was too controversial to ignore...',
    'There are few things more awkward than waving at someone who wasn\'t actually waving at you...',
    'It wasn\'t until I checked my pockets that I realized my keys were still inside the locked car...',
    'The thing about old family recipes is that no one ever writes down the important details...',
    'I was going to make a joke, but then I saw the way they were looking at me and decided against it...',
    'The instructions were clear, and yet, somehow, I had still managed to glue my fingers together...',
    'I thought I had seen it all, but then I watched a raccoon steal an entire loaf of bread and run off like it had somewhere to be...',
]