name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create Frontend .env File
        woarking-directory: ./front
        run: |
          echo "${{ secrets.PROD_VITE_APP_ENV_VARS }}" > .env
          tail .env

      - name: Install and Build Frontend
        working-directory: ./front
        run: |
          npm install
          npm run build

      - name: Install Backend
        working-directory: ./back
        run: |
          npm install

      - name: Remove Front Files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/html/memo-minder/front/*

      - name: Transfer Front Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "front/dist/*"
          target: "/var/www/html/memo-minder/front"
          strip_components: 2 # Removes the 'front/dist' portion and only transfers its contents

      - name: Transfer Back Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "back/*"
          target: "/var/www/html/memo-minder/back"
          strip_components: 1 # Removes the 'back' portion and only transfers its contents

      - name: Restart Services on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/html/memo-minder/back
            npm install

            npm run seed

            pm2 start main.js --name memo-minder-backend || pm2 restart memo-minder-backend

            sudo systemctl restart apache2
