name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - 'back/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      # FRONTEND
      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

      - name: Set up Environment Variables
        run: |
          echo "VITE_APP_SHORT_NAME=${{ secrets.PROD_VITE_APP_SHORT_NAME }}" >> .env
          echo "VITE_APP_NAME=${{ secrets.PROD_VITE_APP_NAME }}" >> .env
          echo "VITE_APP_COMPANY_NAME=${{ secrets.PROD_VITE_APP_COMPANY_NAME }}" >> .env
          echo "VITE_APP_AUTHOR_NAME=${{ secrets.PROD_VITE_APP_AUTHOR_NAME }}" >> .env
          echo "VITE_APP_DESCRIPTION=${{ secrets.PROD_VITE_APP_DESCRIPTION }}" >> .env
          echo "VITE_APP_THEME_COLOR=${{ secrets.PROD_VITE_APP_THEME_COLOR }}" >> .env
          echo "VITE_APP_BG_COLOR=${{ secrets.PROD_VITE_APP_BG_COLOR }}" >> .env
          echo "VITE_PORT=${{ secrets.PROD_VITE_PORT }}" >> .env
          echo "VITE_FRONT_URL=${{ secrets.PROD_VITE_FRONT_URL }}" >> .env
          echo "VITE_BACK_API_URL=${{ secrets.PROD_VITE_BACK_API_URL }}" >> .env
          echo "VITE_GIT_REPO=${{ secrets.PROD_VITE_GIT_REPO }}" >> .env

      - name: Install and Build frontend
        working-directory: ./front
        run: |
          npm install
          npm run build

      - name: Remove Front files on remote
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/html/memo-minder/front/*

      - name: Transfer Front files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "front/dist/*"
          target: "/var/www/html/memo-minder/front"
          strip_components: 2 # Removes the 'front/dist' portion and only transfers its contents

      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      # BACKEND
      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

      - name: Transfer Back Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "back/*"
          target: "/var/www/html/memo-minder/back"
          strip_components: 1 # Removes the 'back' portion and only transfers its contents

      - name: Install Backend Dependencies and Restart node server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/html/memo-minder/back
            npm install

            pm2 start main.js --name memo-minder-backend || pm2 restart memo-minder-backend

      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      # APACHE
      # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

      - name: Restart Apache server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
